//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRES
    {
        public int ID { get; set; }
        public string TELEFON { get; set; }
        public string MAIL { get; set; }
        public string ADRES1 { get; set; }
        public string KONUM { get; set; }
    }
}
