//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVapp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVentityEntities1 : DbContext
    {
        public DbCVentityEntities1()
            : base("name=DbCVentityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADRES> ADRES { get; set; }
        public virtual DbSet<ÇALIŞMALARIM> ÇALIŞMALARIM { get; set; }
        public virtual DbSet<ILETISIM> ILETISIM { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDA { get; set; }
        public virtual DbSet<YETENEKLER> YETENEKLER { get; set; }
        public virtual DbSet<ADMIN> ADMIN { get; set; }
    }
}
